<?php
namespace Miczone\Thrift\Catalog\Product;

/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class SimpleProduct
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'id',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'source',
            'isRequired' => true,
            'type' => TType::STRUCT,
            'class' => '\Miczone\Thrift\Catalog\Source\SimpleSource',
        ),
        3 => array(
            'var' => 'originalMerchant',
            'isRequired' => true,
            'type' => TType::STRUCT,
            'class' => '\Miczone\Thrift\Catalog\OriginalMerchant\SimpleOriginalMerchant',
        ),
        4 => array(
            'var' => 'sku',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        5 => array(
            'var' => 'name',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        6 => array(
            'var' => 'translatedName',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        7 => array(
            'var' => 'avatar',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var string
     */
    public $id = null;
    /**
     * @var \Miczone\Thrift\Catalog\Source\SimpleSource
     */
    public $source = null;
    /**
     * @var \Miczone\Thrift\Catalog\OriginalMerchant\SimpleOriginalMerchant
     */
    public $originalMerchant = null;
    /**
     * @var string
     */
    public $sku = null;
    /**
     * @var string
     */
    public $name = null;
    /**
     * @var string
     */
    public $translatedName = null;
    /**
     * @var string
     */
    public $avatar = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['id'])) {
                $this->id = $vals['id'];
            }
            if (isset($vals['source'])) {
                $this->source = $vals['source'];
            }
            if (isset($vals['originalMerchant'])) {
                $this->originalMerchant = $vals['originalMerchant'];
            }
            if (isset($vals['sku'])) {
                $this->sku = $vals['sku'];
            }
            if (isset($vals['name'])) {
                $this->name = $vals['name'];
            }
            if (isset($vals['translatedName'])) {
                $this->translatedName = $vals['translatedName'];
            }
            if (isset($vals['avatar'])) {
                $this->avatar = $vals['avatar'];
            }
        }
    }

    public function getName()
    {
        return 'SimpleProduct';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->id);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRUCT) {
                        $this->source = new \Miczone\Thrift\Catalog\Source\SimpleSource();
                        $xfer += $this->source->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRUCT) {
                        $this->originalMerchant = new \Miczone\Thrift\Catalog\OriginalMerchant\SimpleOriginalMerchant();
                        $xfer += $this->originalMerchant->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->sku);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->name);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 6:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->translatedName);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 7:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->avatar);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('SimpleProduct');
        if ($this->id !== null) {
            $xfer += $output->writeFieldBegin('id', TType::STRING, 1);
            $xfer += $output->writeString($this->id);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->source !== null) {
            if (!is_object($this->source)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('source', TType::STRUCT, 2);
            $xfer += $this->source->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->originalMerchant !== null) {
            if (!is_object($this->originalMerchant)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('originalMerchant', TType::STRUCT, 3);
            $xfer += $this->originalMerchant->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->sku !== null) {
            $xfer += $output->writeFieldBegin('sku', TType::STRING, 4);
            $xfer += $output->writeString($this->sku);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->name !== null) {
            $xfer += $output->writeFieldBegin('name', TType::STRING, 5);
            $xfer += $output->writeString($this->name);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->translatedName !== null) {
            $xfer += $output->writeFieldBegin('translatedName', TType::STRING, 6);
            $xfer += $output->writeString($this->translatedName);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->avatar !== null) {
            $xfer += $output->writeFieldBegin('avatar', TType::STRING, 7);
            $xfer += $output->writeString($this->avatar);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
