<?php
namespace Miczone\Thrift\Catalog\Breadcrumb;

/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class MultiGetBreadcrumbListByProductSkuAndOriginalMerchantResponseItem
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'breadcrumbList',
            'isRequired' => true,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\Miczone\Thrift\Catalog\Category\SimpleCategory',
                ),
        ),
    );

    /**
     * @var \Miczone\Thrift\Catalog\Category\SimpleCategory[]
     */
    public $breadcrumbList = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['breadcrumbList'])) {
                $this->breadcrumbList = $vals['breadcrumbList'];
            }
        }
    }

    public function getName()
    {
        return 'MultiGetBreadcrumbListByProductSkuAndOriginalMerchantResponseItem';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::LST) {
                        $this->breadcrumbList = array();
                        $_size9 = 0;
                        $_etype12 = 0;
                        $xfer += $input->readListBegin($_etype12, $_size9);
                        for ($_i13 = 0; $_i13 < $_size9; ++$_i13) {
                            $elem14 = null;
                            $elem14 = new \Miczone\Thrift\Catalog\Category\SimpleCategory();
                            $xfer += $elem14->read($input);
                            $this->breadcrumbList []= $elem14;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('MultiGetBreadcrumbListByProductSkuAndOriginalMerchantResponseItem');
        if ($this->breadcrumbList !== null) {
            if (!is_array($this->breadcrumbList)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('breadcrumbList', TType::LST, 1);
            $output->writeListBegin(TType::STRUCT, count($this->breadcrumbList));
            foreach ($this->breadcrumbList as $iter15) {
                $xfer += $iter15->write($output);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
