<?php
namespace Miczone\Thrift\Catalog\ProductCondition;

/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class ProductConditionEnum
{
    const ANY = 0;

    const NEW = 1;

    const USED = 2;

    const COLLECTIBLE = 3;

    const REFURBISHED = 4;

    static public $__names = array(
        0 => 'ANY',
        1 => 'NEW',
        2 => 'USED',
        3 => 'COLLECTIBLE',
        4 => 'REFURBISHED',
    );
}

