<?php
namespace Miczone\Thrift\Catalog\Search;

/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class SearchProductResponseDataRefinement
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'categoryGroup',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Miczone\Thrift\Catalog\Search\SearchProductResponseDataRefinementCategoryGroup',
        ),
        2 => array(
            'var' => 'otherGroupList',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\Miczone\Thrift\Catalog\Search\SearchProductResponseDataRefinementOtherGroup',
                ),
        ),
    );

    /**
     * @var \Miczone\Thrift\Catalog\Search\SearchProductResponseDataRefinementCategoryGroup
     */
    public $categoryGroup = null;
    /**
     * @var \Miczone\Thrift\Catalog\Search\SearchProductResponseDataRefinementOtherGroup[]
     */
    public $otherGroupList = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['categoryGroup'])) {
                $this->categoryGroup = $vals['categoryGroup'];
            }
            if (isset($vals['otherGroupList'])) {
                $this->otherGroupList = $vals['otherGroupList'];
            }
        }
    }

    public function getName()
    {
        return 'SearchProductResponseDataRefinement';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->categoryGroup = new \Miczone\Thrift\Catalog\Search\SearchProductResponseDataRefinementCategoryGroup();
                        $xfer += $this->categoryGroup->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::LST) {
                        $this->otherGroupList = array();
                        $_size42 = 0;
                        $_etype45 = 0;
                        $xfer += $input->readListBegin($_etype45, $_size42);
                        for ($_i46 = 0; $_i46 < $_size42; ++$_i46) {
                            $elem47 = null;
                            $elem47 = new \Miczone\Thrift\Catalog\Search\SearchProductResponseDataRefinementOtherGroup();
                            $xfer += $elem47->read($input);
                            $this->otherGroupList []= $elem47;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('SearchProductResponseDataRefinement');
        if ($this->categoryGroup !== null) {
            if (!is_object($this->categoryGroup)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('categoryGroup', TType::STRUCT, 1);
            $xfer += $this->categoryGroup->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->otherGroupList !== null) {
            if (!is_array($this->otherGroupList)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('otherGroupList', TType::LST, 2);
            $output->writeListBegin(TType::STRUCT, count($this->otherGroupList));
            foreach ($this->otherGroupList as $iter48) {
                $xfer += $iter48->write($output);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
